# Generated by Django 5.2.6 on 2025-12-30 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_bep20_id_profile_bitcoin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_avatar', max_length=255, null=True, verbose_name='profile'),
        ),
    ]
