# Generated by Django 5.2.6 on 2026-01-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
