# Generated by Django 5.2.6 on 2025-10-15 13:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chain', models.CharField(choices=[('ethereum', 'Ethereum (ERC20)'), ('bsc', 'Binance Smart Chain (BEP20)')], max_length=32)),
                ('xpub', models.TextField(blank=True, help_text='Extended public key to derive deposit addresses (no priv keys!)', null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=128)),
                ('derivation_index', models.BigIntegerField(blank=True, help_text='Child index used to derive address (if using XPUB)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to=settings.AUTH_USER_MODEL)),
                ('platform_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to='payment.platformwallet')),
            ],
            options={
                'unique_together': {('user', 'platform_wallet')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('kind', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=32)),
                ('to_address', models.CharField(max_length=128)),
                ('chain', models.CharField(choices=[('ethereum', 'Ethereum (ERC20)'), ('bsc', 'Binance Smart Chain (BEP20)')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(db_index=True, max_length=128)),
                ('from_address', models.CharField(blank=True, max_length=128, null=True)),
                ('token_contract', models.CharField(blank=True, help_text='Token contract address (USDT)', max_length=128, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=18, help_text='Amount in token base units (human readable)', max_digits=32, null=True)),
                ('amount_raw', models.DecimalField(blank=True, decimal_places=0, help_text='Raw integer (token contract decimals applied)', max_digits=64, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credited', models.BooleanField(default=False, help_text="Whether user's internal balance was credited")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('deposit_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.depositaddress')),
                ('platform_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.platformwallet')),
            ],
            options={
                'indexes': [models.Index(fields=['tx_hash'], name='payment_dep_tx_hash_0754e2_idx'), models.Index(fields=['status'], name='payment_dep_status_c291c1_idx')],
            },
        ),
    ]
