# Generated by Django 5.2.6 on 2025-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaddress',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='depositaddress',
            name='derivation_index',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
