# Generated by Django 5.2.6 on 2025-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_depositaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount_raw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=64, null=True),
        ),
    ]
