# Generated by Django 5.2.6 on 2025-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_deposit_amount_alter_deposit_amount_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformwallet',
            name='chain',
            field=models.CharField(choices=[('ethereum', 'Ethereum (ERC20)'), ('bsc', 'Binance Smart Chain (BEP20)'), ('tron', 'Tron (TRC20)'), ('bitcoin', 'Bitcoin (BTC)'), ('solana', 'Solana (SOL)'), ('polygon', 'Polygon (MATIC)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='chain',
            field=models.CharField(choices=[('ethereum', 'Ethereum (ERC20)'), ('bsc', 'Binance Smart Chain (BEP20)'), ('tron', 'Tron (TRC20)'), ('bitcoin', 'Bitcoin (BTC)'), ('solana', 'Solana (SOL)'), ('polygon', 'Polygon (MATIC)')], max_length=32),
        ),
    ]
