# Generated by Django 5.2.6 on 2025-12-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investmentintent'),
        ('payment', '0005_p2ptransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='investment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investmentintent'),
        ),
        migrations.AddField(
            model_name='platformwallet',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
