# Generated by Django 5.2.6 on 2025-12-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_deposit_investment_intent_platformwallet_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='p2ptransfer',
            options={},
        ),
        migrations.AddField(
            model_name='p2ptransfer',
            name='chain',
            field=models.CharField(choices=[('tron', 'TRON'), ('usdt_trc20', 'USDT (TRC20)'), ('ethereum', 'Ethereum (ETH)'), ('usdt_erc20', 'USDT (ERC20)'), ('bitcoin', 'Bitcoin (BTC)')], default='tron', max_length=20),
        ),
        migrations.AlterField(
            model_name='p2ptransfer',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='p2ptransfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_p2p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='p2ptransfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_p2p', to=settings.AUTH_USER_MODEL),
        ),
    ]
