# Generated by Django 5.2.6 on 2025-12-29 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_p2ptransfer_options_p2ptransfer_chain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'reference'], name='payment_tra_user_id_351ef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', None), _negated=True), fields=('user', 'reference'), name='unique_tx_reference_per_user'),
        ),
    ]
