# Generated by Django 5.2.6 on 2026-03-21 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_p2ptransfer_completed_at_p2ptransfer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='admin_approved',
            field=models.BooleanField(default=False, help_text="Admin must approve this deposit before it is credited to the user's balance."),
        ),
        migrations.AddField(
            model_name='deposit',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved this deposit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='token_contract',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='platformwallet',
            name='xpub',
            field=models.TextField(blank=True, null=True),
        ),
    ]
