# Generated by Django 5.2.6 on 2025-10-14 04:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profit_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_hours', models.PositiveIntegerField()),
                ('min_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('automated_payout', models.BooleanField(default=True)),
                ('instant_withdrawal', models.BooleanField(default=True)),
                ('referral_bonus_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_payout_done', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='investment.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Investment',
                'verbose_name_plural': 'User Investments',
                'ordering': ['-start_time'],
            },
        ),
    ]
