# Generated by Django 5.2.6 on 2025-12-30 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_document',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfie',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
