# Generated by Django 5.2.6 on 2026-02-27 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycverification_id_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycverification',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'KYC Verification', 'verbose_name_plural': 'KYC Verifications'},
        ),
        migrations.AddField(
            model_name='kycverification',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes (not shown to user)'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason shown to the user when their KYC is rejected'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last reviewed this KYC submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
